TARGETS = kjl_275i_log_linear_tbl_cvt

kjl_275i_log_linear_tbl_cvt:
	gcc -Wall -o kjl_275i_log_linear_tbl_cvt kjl_275i_log_linear_tbl_cvt.c 
	kjl_275i_log_linear_tbl_cvt < kjl_275i_log_linear_tbl

clean:
	rm -f $(TARGETS) *.o

